name: Publish
on:
  push:
    branches:
      - master
      - newbuild
    paths:
      - RELEASE_NOTES.md
      - .github/workflows/publish.yml
jobs:
  pack:
    name: Package
    runs-on: windows-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: GIT remote
        shell: cmd
        run: git remote get-url
      - name: Install Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'
      - name: Restore Tools
        run: dotnet tool restore
      - name: Restore
        run: dotnet paket restore
      - name: Build
        shell: cmd
        run: dotnet build -c Release buildtest.fsproj
      - name: Pack
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: dotnet aardpack buildtest.fsproj
      - name: Upload Packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: bin\pack
      # - name: NuGet
      #   env:
      #     NUGET_KEY: ${{ secrets.NUGET_KEY }}
      #   shell: cmd
      #   run: dotnet nuget push "bin\pack\*.nupkg" -k %NUGET_KEY% -s "https://api.nuget.org/v3/index.json" --skip-duplicate